/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrapbookRouteImport } from './routes/scrapbook'
import { Route as DossiersRouteImport } from './routes/dossiers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BookBuilderRouteImport } from './routes/book-builder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewerIdRouteImport } from './routes/viewer.$id'
import { Route as AdminCreateRouteImport } from './routes/admin.create'

const ScrapbookRoute = ScrapbookRouteImport.update({
  id: '/scrapbook',
  path: '/scrapbook',
  getParentRoute: () => rootRouteImport,
} as any)
const DossiersRoute = DossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBuilderRoute = BookBuilderRouteImport.update({
  id: '/book-builder',
  path: '/book-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIdRoute = ViewerIdRouteImport.update({
  id: '/viewer/$id',
  path: '/viewer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-builder': typeof BookBuilderRoute
  '/discover': typeof DiscoverRoute
  '/dossiers': typeof DossiersRoute
  '/scrapbook': typeof ScrapbookRoute
  '/admin/create': typeof AdminCreateRoute
  '/viewer/$id': typeof ViewerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-builder': typeof BookBuilderRoute
  '/discover': typeof DiscoverRoute
  '/dossiers': typeof DossiersRoute
  '/scrapbook': typeof ScrapbookRoute
  '/admin/create': typeof AdminCreateRoute
  '/viewer/$id': typeof ViewerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book-builder': typeof BookBuilderRoute
  '/discover': typeof DiscoverRoute
  '/dossiers': typeof DossiersRoute
  '/scrapbook': typeof ScrapbookRoute
  '/admin/create': typeof AdminCreateRoute
  '/viewer/$id': typeof ViewerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-builder'
    | '/discover'
    | '/dossiers'
    | '/scrapbook'
    | '/admin/create'
    | '/viewer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/book-builder'
    | '/discover'
    | '/dossiers'
    | '/scrapbook'
    | '/admin/create'
    | '/viewer/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book-builder'
    | '/discover'
    | '/dossiers'
    | '/scrapbook'
    | '/admin/create'
    | '/viewer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookBuilderRoute: typeof BookBuilderRoute
  DiscoverRoute: typeof DiscoverRoute
  DossiersRoute: typeof DossiersRoute
  ScrapbookRoute: typeof ScrapbookRoute
  ViewerIdRoute: typeof ViewerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrapbook': {
      id: '/scrapbook'
      path: '/scrapbook'
      fullPath: '/scrapbook'
      preLoaderRoute: typeof ScrapbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossiers': {
      id: '/dossiers'
      path: '/dossiers'
      fullPath: '/dossiers'
      preLoaderRoute: typeof DossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-builder': {
      id: '/book-builder'
      path: '/book-builder'
      fullPath: '/book-builder'
      preLoaderRoute: typeof BookBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/$id': {
      id: '/viewer/$id'
      path: '/viewer/$id'
      fullPath: '/viewer/$id'
      preLoaderRoute: typeof ViewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCreateRoute: typeof AdminCreateRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreateRoute: AdminCreateRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookBuilderRoute: BookBuilderRoute,
  DiscoverRoute: DiscoverRoute,
  DossiersRoute: DossiersRoute,
  ScrapbookRoute: ScrapbookRoute,
  ViewerIdRoute: ViewerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
